version: '2'
services:
  wsbb:
    image: salas/wsbb-docker
    build: .
    devices:
      - /dev/snd:/dev/snd
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/ff/.Xauthority
      - HOST_HOSTNAME=${HOSTNAME}
    cpuset: '0'
    mem_limit: 1024M
    shm_size: 2g
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:/tmp/.docker.xauth:ro
      - ~/Downloads:/home/ff/Downloads
      
